//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNPPlib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SNPPlib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller id must be numeric..
        /// </summary>
        internal static string CallerIdNumeric {
            get {
                return ResourceManager.GetString("CallerIdNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A caller id is required..
        /// </summary>
        internal static string CallerIdRequired {
            get {
                return ResourceManager.GetString("CallerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured hostname is invalid..
        /// </summary>
        internal static string ConfigInvalidHostname {
            get {
                return ResourceManager.GetString("ConfigInvalidHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured value is not valid for this type..
        /// </summary>
        internal static string ConfigInvalidType {
            get {
                return ResourceManager.GetString("ConfigInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SNPP configuration section was not found..
        /// </summary>
        internal static string ConfigNotFound {
            get {
                return ResourceManager.GetString("ConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured value is not outside specified range..
        /// </summary>
        internal static string ConfigNotOutsideRange {
            get {
                return ResourceManager.GetString("ConfigNotOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured value is outside specified range..
        /// </summary>
        internal static string ConfigOutsideRange {
            get {
                return ResourceManager.GetString("ConfigOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration for the SNPPP server &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ConfigServerNotFound {
            get {
                return ResourceManager.GetString("ConfigServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured attempting to connect to the server..
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login id must be alphanumeric..
        /// </summary>
        internal static string LoginIdAlphanumeric {
            get {
                return ResourceManager.GetString("LoginIdAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A login id is required..
        /// </summary>
        internal static string LoginIdRequired {
            get {
                return ResourceManager.GetString("LoginIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message must be alphanumeric..
        /// </summary>
        internal static string MessageAlphanumeric {
            get {
                return ResourceManager.GetString("MessageAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message must contain at least one line of text..
        /// </summary>
        internal static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager id must be numeric..
        /// </summary>
        internal static string PagerIdNumeric {
            get {
                return ResourceManager.GetString("PagerIdNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one pager is required..
        /// </summary>
        internal static string PagerRequired {
            get {
                return ResourceManager.GetString("PagerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject must be alphanumeric..
        /// </summary>
        internal static string SubjectAlphanumeric {
            get {
                return ResourceManager.GetString("SubjectAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subject is required..
        /// </summary>
        internal static string SubjectTextRequired {
            get {
                return ResourceManager.GetString("SubjectTextRequired", resourceCulture);
            }
        }
    }
}
